[tool.poetry]
name = "seat-arranger"
version = "0.1.0"
description = ""
authors = ["Anthony Panettiere <apanettiere@fastmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.13"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
